source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '10.0'

target 'ZZMakeAVPlayer_Example' do
  pod 'ZZMakeAVPlayer', :path => '../'

  target 'ZZMakeAVPlayer_Tests' do
    inherit! :search_paths

    
  end
end
